### ISSUE TITLE
Color major version upgrade has breaking changes

### ISSUE THREAD

**Issue by PrashantMohta** [3rd-Eden/colorspace#8]
Color major version upgrade has breaking changes, could you perhaps bump your major version too? 
This change ends up getting included in our build process via other packages that have not seen a release in years and breaking things, would be happy to raise a PR if needed.

suggested solution : downgrade color version to last stable version and do a patch release for colorspace and then if u intend to upgrade color, then update the major version of this package as well in a new release.

cheers!

**Comment by timothy-tsang** [comment]
Same issue - please fix this as it is breaking many applications that may use a lower Node version

**Comment by 3rd-Eden** [comment]
Just saw this. Plan of attack:

1. Revert commit
2. Publish new minor
3. Grab a beer
4. Worry about the upgrade later

**Comment by 3rd-Eden** [comment]
Published 1.1.4 which should resolve the issues. Guess I will need to look at the tests, as it's passing with the upgrade.

**Comment by timothy-tsang** [comment]
Thanks @3rd-Eden , the revert looks like it worked. Thank you!

**Comment by 3rd-Eden** [comment]
I'm interested to know what exactly broke though, because the tests aren't showing any failures and this code base literally like 10 lines of code that does things.

**Comment by timothy-tsang** [comment]
For me specifically, I am using the library **Winston**, which uses a dependency called **Diagnostics**, which uses Colorspace. In our package-lock.json, Diagnostics sets the version of colorspace as: 1.1.x. Hence, when installing, it installed 1.1.3 instead of 1.1.2. Colorspace uses color, which we got error messages from.


The error messages we got were:
```
node_modules/colorspace/node_modules/color/index.js:257

lum[i] = (chan <= 0.039_28) ? chan / 12.92 : ((chan + 0.055) / 1.055) ** 2.4;
		  ^^^^^
```

**Comment by PrashantMohta** [comment]
Great, thanks! @3rd-Eden 

as for what broke, basically color 4.0.0 is using _ in number literals which ends up breaking older setups 
relevant issue on color github https://github.com/Qix-/color/issues/204

Colorspace ends up being included thanks to a dependency `Diagnostics` in our project as well.

**Comment by 3rd-Eden** [comment]
Ah, that explains why the tests are passing and all output is as expected! Thanks for the information <3 much appreciated. 

I make a note to also fix `diagnostics` by pinning the version better. 

Gotta see what I can do to prevent issues like these happening in the future because it would be nice if the test suite somehow caught this.

**Comment by justinnichols** [comment]
> Gotta see what I can do to prevent issues like these happening in the future because it would be nice if the test suite somehow caught this.

It became obvious to us because our NodeJS version was too low to support the downstream 4.0.0 color library version which is what exhibited this error.  Perhaps having the test suite test use the lowest NodeJS version you support would help (or even test against multiple LTS versions).  Only a humble suggestion and thanks for fixing this so quickly.
